trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@2
  displayName: "Terraform init"
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial (e191435e-1cdf-467f-94f5-b1c6c10bede5)'
    allowTelemetryCollection: false

- task: Bash@3
  displayName: "Collect workspace details"
  inputs:
    targetType: 'inline'
    script: 'echo "##vso[task.setvariable variable=workspace]$(cat environment_to_deploy.json|awk -F'': '' ''/env/{print $2}''|sed ''s/"//g'')"'

- task: TerraformCLI@2
  displayName: "Select workspace"
  inputs:
    command: 'workspace'
    allowTelemetryCollection: true
    workspaceName: '$(workspace)'

- task: TerraformCLI@2
  displayName: "Terraform apply"
  inputs:
    command: 'apply'
    environmentServiceName: 'Free Trial (e191435e-1cdf-467f-94f5-b1c6c10bede5)'
    commandOptions: '-var-file $(workspace).tfvars'
    allowTelemetryCollection: false